config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
end

  # Read all restaurants
  # get '/restaurants', to: 'restaurants#index'
  # # Read one restaurant
  # # Always put the new route before the show
  # get '/restaurants/new', to: 'restaurants#new' # display a blank form
  # get '/restaurants/:id', to: 'restaurants#show', as: :restaurant
  # # Create a restaurant
  # post '/restaurants', to: 'restaurants#create' # once user has filled in the inputs and the restaurant is posted to the server
  # # Update a restaurant
  # get '/restaurants/:id/edit', to: 'restaurants#edit' # display a prefilled form
  # patch '/restaurants/:id', to: 'restaurants#update' # to patch the new updated instance to server
  # # Delete a restaurant
  # delete '/restaurants/:id', to: 'restaurants#destroy'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #before_action :set_task, only: [:show, :edit, :update, :destroy]

  # CRUD ACTIONS - to aid the user stories

  def index # Read all
    @tasks = Task.all
  end

  def show # Read all
    # raise - stop code to look inside params
    @task = Task.find(params[:id])
  end

  def new # Empty instance of a restaurant to display the blank form
    @task = Task.new
  end

  def create # Create a restaurant, post it to the DB
    @task = Task.new(strong_task_params) # Create restaurant with strong params - the params that I have allowed
    @task.save
    redirect_to task_path(@task) # Redirect to the restaurant I just created (UX reason - no view for the create action)
  end

  def edit # Instance of the restaurant to be updated for the form
    @task = Task.find(params[:id])
  end

  def update # Update instance of the restaurant in the DB
    @task = Task.find(params[:id])
    @task.update(strong_task_params)

    redirect_to task_path(@task) # Redirect to the restaurant I just updated (UX reason - no view for the update action)
  end

  def destroy # Delete a restaurant instance from DB
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  # SECURITY MEASURE
  def strong_task_params # Whitelist approach - you specify which keys in the params hash you allow

    params.require(:task).permit(:title, :details, :completed)
    # params = {
      #   restaurant = { name: "Ishin", address: "Mitte",rating: 4 }
      # }
   end


   # def set_task
   #  @task = Task.find(params[:id])
   # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<!-- app/views/restaurants/index.html.erb -->
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><p>    <%= task.completed == true ? '✓' : '𐄂' %>
      <%= link_to task.title, task_path(task) %>
    </p></li>
  <% end %>
</ul>
<%= link_to "Create new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>My Tasks</h1>
<p><%= @task.details %></p>

<%= link_to "Show all tasks", tasks_path %>
<%= link_to "Edit task", task_edit_path %>
<%= link_to 'Delete task', task_path(@task), method: :delete, data: { confirm: "Are you sure you want to delete?"}   %>